name: Flask Docker Build and push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: flask-app-gitactions

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repository
        uses: actions/checkout@v4

      - name: Docker build and push and tag using composite action 
        uses: ./.github/actions/docker-build-push
        with:
          docker_user: ${{secret.DOCKER_USER}}
          docker_password: ${{secret.DOCKER_PASSWORD}}
          image_name: $IMAGE_NAME
      - name: create build report
        run: |
          echo "Application: flask-app-gitactions" > build-report.txt
          echo "Image: ${{secrets.DOCKER_USER}}/$IMAGE_NAME:latest" >> build-report.txt
          echo "Build status : success" >> build-report.txt
          echo "Build time: $(date)" >> build-report.txt
      - name: upload build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Flask-build-report
          path: build-report.txt       
              
        
          
